-- Đồng bộ mã kỹ năng giữa AI service và backend. Đây là từ điển cục bộ, không phải mã ESCO chính thức.
INSERT INTO skill_taxonomies (id, skill_name, category, framework, aliases, taxonomy_version)
VALUES
    ('SK-JS', 'JavaScript', 'TECHNICAL', 'INTERNLINK', '["js", "es6", "ecmascript"]'::jsonb, 'v1.0'),
    ('SK-TS', 'TypeScript', 'TECHNICAL', 'INTERNLINK', '["ts"]'::jsonb, 'v1.0'),
    ('SK-CSHARP', 'C#', 'TECHNICAL', 'INTERNLINK', '["c sharp", ".net c#"]'::jsonb, 'v1.0'),
    ('SK-CPP', 'C++', 'TECHNICAL', 'INTERNLINK', '["c/c++", "cpp"]'::jsonb, 'v1.0'),
    ('SK-GOLANG', 'Go', 'TECHNICAL', 'INTERNLINK', '["golang"]'::jsonb, 'v1.0'),
    ('SK-PHP', 'PHP', 'TECHNICAL', 'INTERNLINK', '["php 8"]'::jsonb, 'v1.0'),
    ('SK-KOTLIN', 'Kotlin', 'TECHNICAL', 'INTERNLINK', '["android kotlin"]'::jsonb, 'v1.0'),
    ('SK-SWIFT', 'Swift', 'TECHNICAL', 'INTERNLINK', '["ios swift"]'::jsonb, 'v1.0'),
    ('SK-SQL', 'SQL', 'TECHNICAL', 'INTERNLINK', '["structured query language", "t-sql", "pl/sql"]'::jsonb, 'v1.0'),
    ('SK-NESTJS', 'NestJS', 'TECHNICAL', 'INTERNLINK', '["nest.js", "nest js"]'::jsonb, 'v1.0'),
    ('SK-EXPRESS', 'Express.js', 'TECHNICAL', 'INTERNLINK', '["express", "expressjs"]'::jsonb, 'v1.0'),
    ('SK-DJANGO', 'Django', 'TECHNICAL', 'INTERNLINK', '["django rest framework", "drf"]'::jsonb, 'v1.0'),
    ('SK-DOTNET', '.NET Core', 'TECHNICAL', 'INTERNLINK', '["asp.net", "asp.net core", ".net", "dotnet"]'::jsonb, 'v1.0'),
    ('SK-NODEJS', 'Node.js', 'TECHNICAL', 'INTERNLINK', '["nodejs", "node"]'::jsonb, 'v1.0'),
    ('SK-NEXTJS', 'Next.js', 'TECHNICAL', 'INTERNLINK', '["nextjs", "next js"]'::jsonb, 'v1.0'),
    ('SK-VUE', 'Vue.js', 'TECHNICAL', 'INTERNLINK', '["vue", "vuejs", "vue 3"]'::jsonb, 'v1.0'),
    ('SK-ANGULAR', 'Angular', 'TECHNICAL', 'INTERNLINK', '["angular 2+", "angularjs"]'::jsonb, 'v1.0'),
    ('SK-TAILWIND', 'Tailwind CSS', 'TECHNICAL', 'INTERNLINK', '["tailwind", "tailwindcss"]'::jsonb, 'v1.0'),
    ('SK-HTML-CSS', 'HTML/CSS', 'TECHNICAL', 'INTERNLINK', '["html", "css", "html5", "css3"]'::jsonb, 'v1.0'),
    ('SK-FLUTTER', 'Flutter', 'TECHNICAL', 'INTERNLINK', '["dart", "flutter app"]'::jsonb, 'v1.0'),
    ('SK-REACT-NATIVE', 'React Native', 'TECHNICAL', 'INTERNLINK', '["rn", "react-native"]'::jsonb, 'v1.0'),
    ('SK-MYSQL', 'MySQL', 'TECHNICAL', 'INTERNLINK', '["mariadb"]'::jsonb, 'v1.0'),
    ('SK-MONGODB', 'MongoDB', 'TECHNICAL', 'INTERNLINK', '["mongo", "nosql mongodb"]'::jsonb, 'v1.0'),
    ('SK-REDIS', 'Redis', 'TECHNICAL', 'INTERNLINK', '["redis cache"]'::jsonb, 'v1.0'),
    ('SK-ORACLE', 'Oracle DB', 'TECHNICAL', 'INTERNLINK', '["oracle database"]'::jsonb, 'v1.0'),
    ('SK-KUBERNETES', 'Kubernetes', 'TECHNICAL', 'INTERNLINK', '["k8s"]'::jsonb, 'v1.0'),
    ('SK-CICD', 'CI/CD', 'TECHNICAL', 'INTERNLINK', '["continuous integration", "github actions", "gitlab ci", "jenkins"]'::jsonb, 'v1.0'),
    ('SK-AWS', 'Amazon Web Services (AWS)', 'TECHNICAL', 'INTERNLINK', '["aws", "ec2", "s3", "lambda"]'::jsonb, 'v1.0'),
    ('SK-AZURE', 'Microsoft Azure', 'TECHNICAL', 'INTERNLINK', '["azure"]'::jsonb, 'v1.0'),
    ('SK-GCP', 'Google Cloud Platform (GCP)', 'TECHNICAL', 'INTERNLINK', '["gcp", "google cloud"]'::jsonb, 'v1.0'),
    ('SK-LINUX', 'Linux', 'TECHNICAL', 'INTERNLINK', '["ubuntu", "bash", "shell script"]'::jsonb, 'v1.0'),
    ('SK-GRAPHQL', 'GraphQL', 'TECHNICAL', 'INTERNLINK', '["apollo"]'::jsonb, 'v1.0'),
    ('SK-MICROSERVICES', 'Microservices', 'TECHNICAL', 'INTERNLINK', '["microservice architecture", "distributed systems"]'::jsonb, 'v1.0'),
    ('SK-OOP', 'Object-Oriented Programming (OOP)', 'TECHNICAL', 'INTERNLINK', '["oop", "lập trình hướng đối tượng"]'::jsonb, 'v1.0'),
    ('SK-DESIGN-PATTERNS', 'Design Patterns', 'TECHNICAL', 'INTERNLINK', '["mô hình thiết kế", "solid"]'::jsonb, 'v1.0'),
    ('SK-UNIT-TEST', 'Unit Testing', 'TECHNICAL', 'INTERNLINK', '["junit", "mockito", "jest", "py-test", "testing"]'::jsonb, 'v1.0'),
    ('SK-PROBLEM-SOLVING', 'Giải quyết vấn đề (Problem Solving)', 'SOFT_SKILL', 'INTERNLINK', '["problem solving", "tư duy logic", "analytical thinking"]'::jsonb, 'v1.0'),
    ('SK-ENGLISH', 'Tiếng Anh chuyên ngành (English)', 'TECHNICAL', 'INTERNLINK', '["english", "toeic", "ielts", "tiếng anh"]'::jsonb, 'v1.0')
ON CONFLICT (id) DO NOTHING;
